# Use a imagem oficial do PostgreSQL
FROM postgres:17.6


RUN mkdir -p /var/lib/postgresql/sandbox

# Copiar arquivos de schema e migrations para o container
COPY schemas/ /schemas/
COPY migrations/ /migrations/

# Expor a porta padrão do PostgreSQL
EXPOSE 5432